name: Build Firmware

on:
  push:
    branches: [vial]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli@sha256:16c4916e95b99bf88d27b15aec8db409ee17265d1710287fde248c6666508966

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure Git
        run: git config --global --add safe.directory $(pwd)

      - name: Cache QMK build
        uses: actions/cache@v3
        with:
          path: |
            .build
            *.hex
            *.bin
            *.uf2
          key: ${{ runner.os }}-qmk-${{ hashFiles('keyboards/crkbd/keymaps/nodzba/**/*') }}
          restore-keys: |
            ${{ runner.os }}-qmk-

      - name: Build firmware
        run: qmk compile -kb crkbd -km nodzba

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::release_$(date +"%Y.%m.%d_%H-%M")"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          release_name: Firmware Release ${{ steps.tag.outputs.release_tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./.build/crkbd_rev1_nodzba.uf2
          asset_name: crkbd_rev1_nodzba.uf2
          asset_content_type: application/octet-stream
